### ISSUE TITLE
Unable to use in Android 23 due to noclassdeffounderror: ljava/util/optional

### ISSUE THREAD

**Issue by pasupulaphani** [iotaledger/iota-java#133]
Issue: Unable to use (iota-java:1.0.0-beta2) on Android API < 24 due to the usage of java.util.Optional in [Signing.java](https://github.com/iotaledger/iota-java/blob/master/jota/src/main/java/jota/utils/Signing.java#L12)

There is still a considerable percentage (~22%) of Android users on API 23 Marshmallow. It would be great to set the compatibility, so, that there will be no surprises on Android.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: amiin.bazouk.application.com.demo_bytes_android, PID: 3110
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
        at jota.utils.Signing.<init>(Signing.java:30)
        at jota.utils.IotaAPIUtils.newAddress(IotaAPIUtils.java:39)
        at jota.IotaAPI.generateNewAddresses(IotaAPI.java:148)
        at jota.IotaAPI.getNextAvailableAddress(IotaAPI.java:81)
        at amiin.bazouk.application.com.demo_bytes_android.iota.Iota.getCurrentAddress(Iota.java:88)
        at amiin.bazouk.application.com.demo_bytes_android.iota.Account.getCurrentAddress(Account.java:85)
        at amiin.bazouk.application.com.demo_bytes_android.MainActivity.getBalance(MainActivity.java:762)
        at amiin.bazouk.application.com.demo_bytes_android.MainActivity.access$1600(MainActivity.java:61)
        at amiin.bazouk.application.com.demo_bytes_android.MainActivity$6.onClick(MainActivity.java:244)
        at android.view.View.performClick(View.java:5198)
```

**Comment by jakubcech** [comment]
Hi @pasupulaphani, thanks for the input on this!

**Comment by kwek20** [comment]
@pasupulaphani How do you feel about this library?
https://github.com/stefan-zobel/streamsupport

Backwards compatibility for Java to run on android

**Comment by pasupulaphani** [comment]
thank you @kwek20 I tried that. It failed for some other reason. Let me debug that.

**Comment by pasupulaphani** [comment]
No luck.

**Comment by kwek20** [comment]
What my question was, we could implement that in the library, so you wont have problems with Java 8+.
Sometimes people have problems with using these types of libraries, so i was checking with you.

Or what did you try/is the reason it failed?

**Comment by pasupulaphani** [comment]
Actually, it's the exact same error. I don't think the stream support will automatically import you with the missing module.

**Comment by kwek20** [comment]
It would automatically work of course, I have to manually go through and change all Java streams/optionals to the library streams/optionals :)

**Comment by pasupulaphani** [comment]
Unfortunately, it is a bit of time taking work. But I don't see any problems using streamsupport so far. If you are planning to use streamsupport to make it compatible, in which version can we expect it?

Thank you in advance.

**Comment by ezienecker** [comment]
@kwek20 No feedback on this topic for almost a year and a half. Can't we close the ticket?
