### ISSUE TITLE
sendTransfer with validateInputAddresses set to true fails

### ISSUE THREAD

**Issue by thankthemaker** [iotaledger/iota-java#181]
Using the sendTransfer method with param validateInputAddresses to true leads to error "Invalid addresses provided."

` SendTransferResponse response = api.sendTransfer(SEED,2, depth, minWeightMagnitude, transfers, null, null, true, true, null);
`

`Caused by: org.iota.jota.error.ArgumentException: [Invalid addresses provided.]
        at org.iota.jota.IotaAPICore.getBalances(IotaAPICore.java:461)
        at org.iota.jota.IotaAPICore.getBalances(IotaAPICore.java:492)
        at org.iota.jota.IotaAPI.getBalanceAndFormat(IotaAPI.java:866)
        at org.iota.jota.IotaAPI.getInputs(IotaAPI.java:809)
        at org.iota.jota.IotaAPI.validateTransfersAddresses(IotaAPI.java:1501)
        at org.iota.jota.IotaAPI.sendTransfer(IotaAPI.java:1150)
`

In my opinion this is because getInputs is called with start, end and threshold all set to zero and so no address is returned.

`GetBalancesAndFormatResponse gbr = getInputs(seed, security, 0, 0, 0);
`

**Comment by kwek20** [comment]
Hey @thankthemaker, can you try again on our new release?
1.0.0-beta6

Im pretty sure this has been fixed in there, as we shuffled things around, and a lot more tests

**Comment by thankthemaker** [comment]
Yes, it works again.
