### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Not enough balance

### ISSUE THREAD

**Issue by arjun7862** [iotaledger/iota-java#189]
i am not to do able solve this issue please help
```
 java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.IllegalStateException: Not enough balance.
        at jota.IotaAPI.getBalanceAndFormat(IotaAPI.java:813)
        at jota.IotaAPI.getInputs(IotaAPI.java:748)
        at jota.IotaAPI.prepareTransfers(IotaAPI.java:667)
        at jota.IotaAPI.sendTransfer(IotaAPI.java:1025)
        at com.example.myapplication.Main2Activity$TaskConnection.prepareTransfer(Main2Activity.java:118)
        at com.example.myapplication.Main2Activity$TaskConnection.doInBackground(Main2Activity.java:80)
        at com.example.myapplication.Main2Activity$TaskConnection.doInBackground(Main2Activity.java:39)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```
Code:
```
        IotaAPI api;
        GetNodeInfoResponse noderesponse;
      GetAccountDataResponse accountData;
        SendTransferResponse resp;
       String preytans;
        GetBalancesAndFormatResponse rsp;
api = new IotaAPI.Builder().protocol("https").host("nodes.thetangle.org").port(("443")).build();
  rsp = api.getInputs(SEED, 2, 0, 6, 0);
                noderesponse = api.getNodeInfo();
                accountData = api.getAccountData(SEED, 2,0,true,0,true,0,6,true,0);
                String trytes = TrytesConverter.asciiToTrytes("my text");
                preytans=prepareTransfer(ADDRESS_TO, trytes);



   public String prepareTransfer(String address_seclevel_2, String trytes) throws ArgumentException {
            List<Transfer> transfers = new ArrayList<Transfer>();
            List<Input> inputList=new ArrayList<>();
            for (int i=0; i<rsp.getInputs().size();i++){
                inputList.add(rsp.getInputs().get(i));
            }
            transfers.add(new Transfer(address_seclevel_2, 1, trytes, trytes)); //3,9
             resp = api.sendTransfer(SEED, 2, 9, 15, transfers, inputList,
                    null, true, true,null);
            if(resp.getSuccessfully()!=null){
                //Transfer successfully!


                for(Transaction tx: resp.getTransactions()) {
                    return tx.getHash();
                }

            }
            return "Handle error here. Something went wrong!";

        }
```

**Comment by kwek20** [comment]
Hello @arjun7862 

Are you sure you are using the correct addresses? Iota java checks addresses starting from 0, but stops once it finds an empty address. Could be that your addresses start at index >0?

Another option is that youre trying to spent funds on the devnet on the mainnet, or vice versa.

Alternatively, if youre sure its all correct, you can disable the checks by setting `validateInputs` to false.

Even better; If you dont need to manage transactions manually, you can take a look at the account module! https://docs.iota.org/docs/iota-java/0.1/how-to-guides/create-account
It will manage addresses and balances for you.

**Comment by kwek20** [comment]
Closed due to no reply
