### ISSUE TITLE
URLs containing a path are not supported

### ISSUE THREAD

**Issue by Fredi100** [iotaledger/iota-java#224]
## Bug description

When trying to connect to a node which is behind a proxied address like ``domain.abc/node`` the api can not establish a proper connection throwing an IndexOutOfBoundsException or an UnknownHostException when trying to build the api.

## Version

Which version of the library are you running?

- Version: 1.0.0-beta8

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL: https://tesserekt.net/node
- Network: Private Network

## Hardware specification

What hardware are you using?

- Operating system: Windows 10
- RAM: 32Gb
- Number of cores: 6
- Device type: Desktop PC

## Steps To reproduce the bug

1. Call the ``IotaAPI.Builder()``
2. Set the host to one in this format: ``foo.bar/node``, either check the validity or not
3. Call ``Builder.build()``

Example:
``new IotaAPI.Builder().protocol("https").host("foo.bar\\node",false).port(443).build();``

## Expected behaviour

It should recognize the url as a vaild node like the Javascript api already does.

## Actual behaviour

It throws an IndexOutOfBoundsException when you tell the builder to not check the validity of given address.
It throws an UnknowsHostException when you leave the check active.
Writing a regular ``/`` instead of ``\\`` additionally throws an MalformedURLException as ``/`` is apparently an illegal character in URLs

## Errors

When leaving the check active:
```
java.net.UnknownHostException: Der angegebene Host ist unbekannt (tesserekt.net\node\)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1505)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1495)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1354)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1288)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1238)
	at org.iota.jota.builder.ApiBuilder.host(ApiBuilder.java:111)
	at org.iota.jota.builder.ApiBuilder.host(ApiBuilder.java:128)
	at technikum.iota.instance.Instance.initialize(Instance.java:26)
	at technikum.iota.instance.Instance.<init>(Instance.java:21)
	at technikum.iota.instance.ClientInstance.<init>(ClientInstance.java:9)
	at technikum.iota.instance.Instance.getClientInstance(Instance.java:53)
	at technikum.iota.Main.main(Main.java:22)
```

When deactivating the check:
```
15:14:22.733 [main] WARN org.iota.jota.IotaAPICore - Failed to add node connection to pool due to baseUrl must end in /: https://tesserekt.net/node:443
15:14:22.950 [main] DEBUG org.iota.jota.IotaAccount - Loaded plugin promoter-reattacher
15:14:22.951 [main] DEBUG org.iota.jota.IotaAccount - Loaded plugin IncomingTransferChecker
15:14:22.952 [main] DEBUG org.iota.jota.IotaAccount - Loaded plugin OutgoingTransferChecker
15:14:22.954 [Shutdown Hook] INFO org.iota.jota.IotaAccount - Shutting down IOTA Accounts, please hold tight...

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:426)
	at org.iota.jota.IotaAPICore.getNodeFor(IotaAPICore.java:175)
	at org.iota.jota.IotaAPICore.getNodeInfo(IotaAPICore.java:185)
	at org.iota.jota.IotaAccount.load(IotaAccount.java:215)
	at org.iota.jota.IotaAccount.load(IotaAccount.java:179)
	at org.iota.jota.IotaAccount.<init>(IotaAccount.java:104)
	at org.iota.jota.builder.AccountBuilder.compile(AccountBuilder.java:186)
	at org.iota.jota.builder.AccountBuilder.compile(AccountBuilder.java:37)
	at org.iota.jota.builder.AbstractBuilder.build(AbstractBuilder.java:38)
	at technikum.iota.instance.Instance.initialize(Instance.java:41)
	at technikum.iota.instance.Instance.<init>(Instance.java:21)
	at technikum.iota.instance.ClientInstance.<init>(ClientInstance.java:9)
	at technikum.iota.instance.Instance.getClientInstance(Instance.java:53)
	at technikum.iota.Main.main(Main.java:22)```

**Comment by kwek20** [comment]
@Fredi100 Yes this appears to be an issue, its not expecting the / in there at all, as that is a "path" segment according to URL scheme. I think you can circumvent this using the following code:
`IotaAPI api = new IotaAPI.Builder().addNode(new HttpConnector(new URL("https://tesserekt.net/node/"))).build();`

Let me know if that works, and ill remove the / bug in the next version. A forward slash is suppsoed to end the path in any way. Ill make it so it appends automatically if that works for you?

Let me know how that piece of code worked for you!

**Comment by Fredi100** [comment]
Yeah, with this workaround it's actually possible to add my node. Haven't tested it extensively, but I get a connection to my server with no exceptions.

**Comment by kwek20** [comment]
Glad to hear it!
