### ISSUE TITLE
IllegalAccessError when calling findTransactionsByBundles

### ISSUE THREAD

**Issue by eukaryote31** [iotaledger/iota-java#54]
I'm not sure how to reproduce this error, but I keep finding it in my server logs before iotasear.ch crashes. Any ideas?
```
java.lang.IllegalAccessError: 400
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:73)
	at jota.IotaAPICore.findTransactions(IotaAPICore.java:176)
	at jota.IotaAPICore.findTransactionsByBundles(IotaAPICore.java:184)

```

**Comment by BerserkerInterpreter** [comment]
Which version of IOTA java library are you using?

**Comment by pinpong** [comment]
@eukaryote31 is that issue still present?
